url: http://xiu.shoeke.com
author: Steve Hansen
title: "Steve's Blog"
description: My ideas about Vidyano, .NET, JavaScript, Japanese, ...
avatar: https://avatars2.githubusercontent.com/u/2143488?v=2&s=40
baseurl: ""
markdown: kramdown
exclude: ["README.md", "LICENSE", "CNAME", "Gemfile", "Gemfile.lock"]
timezone: Europe/Brussels
highlighter: pygments
footer-links:
  email: 
  facebook: xiutette
  github: stevehansen
  rss: /feed/
  twitter: HansenSteve
  stackoverflow: users/295296/xiu
disqus: xiu
google_analytics: UA-17536806-1
gems: ["jemoji", "jekyll-sitemap", "jekyll-redirect-from"]
sass:
  sass_dir: _scss
  style: :compressed